name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: ssh pipelines
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "ssh pipeline"
        JWT: ${{ secrets.JWT_SIGNATURE }}
        web: ${{ secrets.REMOTE_TARGET }}
        gmAppPw: ${{ secrets.GMAIL_APP_PW }}
      with:
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        connect_timeout: 10s
        script: | 
          echo $WELCOME
          cd $web
          cp ../knexfile.ts src/database/knexfile.ts
          tsc
          JWT_SIG=$JWT GMAIL_APP_PW=$gmAppPw LIVE='1' pm2 restart server --update-env
